### ISSUE TITLE
Format this repo to work with future events

### ISSUE THREAD

**Issue by MatiasJJ** [coderefinery/workshop-stats#7]
Goal is to make the reporting as straightforward as possible.

• What is the best way to collect data?
• What are the relevant stats to be gathered from all events?

**Comment by MatiasJJ** [comment]
Or maybe make a copy of this repo and name it as workshop-stats-temlpate and make it a template and then rename this to workshop-stats-Sep2022

**Comment by bast** [comment]
Or we could collect all in one place/repo? (here)

**Comment by MatiasJJ** [comment]
Yes that is what happened now

**Comment by MatiasJJ** [comment]
I'll continue with duplicating relevant notebooks for all individual events.
Propably anonymisation notebook works as a general one.

Have to figure out clever way to handle paths also inside notebook.
